<?php

namespace ContainerJMYDVtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxYej41Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wxYej41' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wxYej41'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zone' => ['privates', '.errored..service_locator.wxYej41.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.wxYej41": it needs an instance of "App\\Entity\\Zone" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'zone' => 'App\\Entity\\Zone',
            'entityManager' => '?',
        ]);
    }
}
