<?php

namespace ContainerJMYDVtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OrganisationController' shared autowired service.
     *
     * @return \App\Controller\OrganisationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/OrganisationController.php';

        $container->services['App\\Controller\\OrganisationController'] = $instance = new \App\Controller\OrganisationController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\OrganisationController', $container));

        return $instance;
    }
}
