<?php

namespace ContainerJMYDVtA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pO_aEi_.App\Entity\Organisation' shared service.
     *
     * @return \App\Entity\Organisation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pO_aEi_": it needs an instance of "App\\Entity\\Organisation" but this type has been excluded in "config/services.yaml".');
    }
}
