<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_POAEiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pO_aEi_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pO_aEi_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organisation' => ['privates', '.errored..service_locator.pO_aEi_.App\\Entity\\Organisation', NULL, 'Cannot autowire service ".service_locator.pO_aEi_": it needs an instance of "App\\Entity\\Organisation" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'organisation' => 'App\\Entity\\Organisation',
            'entityManager' => '?',
        ]);
    }
}
