<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VULI7XYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VULI7XY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VULI7XY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'travailler' => ['privates', '.errored..service_locator.VULI7XY.App\\Entity\\Travailler', NULL, 'Cannot autowire service ".service_locator.VULI7XY": it needs an instance of "App\\Entity\\Travailler" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'travailler' => 'App\\Entity\\Travailler',
            'entityManager' => '?',
        ]);
    }
}
