<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeuseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.D21ZqPi.App\Entity\Badgeuse' shared service.
     *
     * @return \App\Entity\Badgeuse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.D21ZqPi": it needs an instance of "App\\Entity\\Badgeuse" but this type has been excluded in "config/services.yaml".');
    }
}
