<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointageControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wL3uK0b.App\Controller\PointageController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wL3uK0b.App\\Controller\\PointageController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointageRepository' => ['privates', 'App\\Repository\\PointageRepository', 'getPointageRepositoryService', true],
        ], [
            'pointageRepository' => 'App\\Repository\\PointageRepository',
        ]))->withContext('App\\Controller\\PointageController::index()', $container);
    }
}
