<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravaillerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TravaillerType' shared autowired service.
     *
     * @return \App\Form\TravaillerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TravaillerType.php';

        return $container->privates['App\\Form\\TravaillerType'] = new \App\Form\TravaillerType();
    }
}
