<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravaillerControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cyu0ZnE.App\Controller\TravaillerController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cyu0ZnE.App\\Controller\\TravaillerController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'travailler' => ['privates', '.errored..service_locator.Cyu0ZnE.App\\Entity\\Travailler', NULL, 'Cannot autowire service ".service_locator.Cyu0ZnE": it needs an instance of "App\\Entity\\Travailler" but this type has been excluded in "config/services.yaml".'],
        ], [
            'travailler' => 'App\\Entity\\Travailler',
        ]))->withContext('App\\Controller\\TravaillerController::show()', $container);
    }
}
