<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravaillerControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VULI7XY.App\Controller\TravaillerController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.VULI7XY'] ?? $container->load('get_ServiceLocator_VULI7XYService'));

        if (isset($container->privates['.service_locator.VULI7XY.App\\Controller\\TravaillerController::edit()'])) {
            return $container->privates['.service_locator.VULI7XY.App\\Controller\\TravaillerController::edit()'];
        }

        return $container->privates['.service_locator.VULI7XY.App\\Controller\\TravaillerController::edit()'] = $a->withContext('App\\Controller\\TravaillerController::edit()', $container);
    }
}
