<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravailler2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VULI7XY.App\Entity\Travailler' shared service.
     *
     * @return \App\Entity\Travailler
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VULI7XY": it needs an instance of "App\\Entity\\Travailler" but this type has been excluded in "config/services.yaml".');
    }
}
