<?php

namespace ContainerU7mrsf9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravaillerControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VULI7XY.App\Controller\TravaillerController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VULI7XY.App\\Controller\\TravaillerController::delete()'] = ($container->privates['.service_locator.VULI7XY'] ?? $container->load('get_ServiceLocator_VULI7XYService'))->withContext('App\\Controller\\TravaillerController::delete()', $container);
    }
}
