<?php

namespace ContainerIYcdCKh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UuXfV1o.App\Entity\Acces' shared service.
     *
     * @return \App\Entity\Acces
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UuXfV1o": it needs an instance of "App\\Entity\\Acces" but this type has been excluded in "config/services.yaml".');
    }
}
