<?php

namespace ContainerIYcdCKh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccesControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UuXfV1o.App\Controller\AccesController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UuXfV1o.App\\Controller\\AccesController::delete()'] = ($container->privates['.service_locator.UuXfV1o'] ?? $container->load('get_ServiceLocator_UuXfV1oService'))->withContext('App\\Controller\\AccesController::delete()', $container);
    }
}
