<?php

namespace ContainerIYcdCKh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wxYej41.App\Controller\ZoneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wxYej41.App\\Controller\\ZoneController::delete()'] = ($container->privates['.service_locator.wxYej41'] ?? $container->load('get_ServiceLocator_WxYej41Service'))->withContext('App\\Controller\\ZoneController::delete()', $container);
    }
}
