<?php

namespace ContainerCZItyM8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oacNTff.App\Controller\ZoneController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oacNTff.App\\Controller\\ZoneController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zone' => ['privates', '.errored..service_locator.oacNTff.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.oacNTff": it needs an instance of "App\\Entity\\Zone" but this type has been excluded in "config/services.yaml".'],
        ], [
            'zone' => 'App\\Entity\\Zone',
        ]))->withContext('App\\Controller\\ZoneController::show()', $container);
    }
}
