<?php

namespace ContainerWndRsXz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7i3.7Gt.App\Controller\OrganisationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7i3.7Gt.App\\Controller\\OrganisationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organisationRepository' => ['privates', 'App\\Repository\\OrganisationRepository', 'getOrganisationRepositoryService', true],
        ], [
            'organisationRepository' => 'App\\Repository\\OrganisationRepository',
        ]))->withContext('App\\Controller\\OrganisationController::index()', $container);
    }
}
