<?php

namespace Container3xwGhM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BelkTOmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.belkTOm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.belkTOm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badgeuse' => ['privates', '.errored..service_locator.belkTOm.App\\Entity\\Badgeuse', NULL, 'Cannot autowire service ".service_locator.belkTOm": it needs an instance of "App\\Entity\\Badgeuse" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'badgeuse' => 'App\\Entity\\Badgeuse',
            'entityManager' => '?',
        ]);
    }
}
