<?php

namespace Container3xwGhM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeuseControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.belkTOm.App\Controller\BadgeuseController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.belkTOm'] ?? $container->load('get_ServiceLocator_BelkTOmService'));

        if (isset($container->privates['.service_locator.belkTOm.App\\Controller\\BadgeuseController::edit()'])) {
            return $container->privates['.service_locator.belkTOm.App\\Controller\\BadgeuseController::edit()'];
        }

        return $container->privates['.service_locator.belkTOm.App\\Controller\\BadgeuseController::edit()'] = $a->withContext('App\\Controller\\BadgeuseController::edit()', $container);
    }
}
