<?php

namespace Container3xwGhM5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BGy84Dx.App\Controller\BadgeController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.BGy84Dx'] ?? $container->load('get_ServiceLocator_BGy84DxService'));

        if (isset($container->privates['.service_locator.BGy84Dx.App\\Controller\\BadgeController::edit()'])) {
            return $container->privates['.service_locator.BGy84Dx.App\\Controller\\BadgeController::edit()'];
        }

        return $container->privates['.service_locator.BGy84Dx.App\\Controller\\BadgeController::edit()'] = $a->withContext('App\\Controller\\BadgeController::edit()', $container);
    }
}
