<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UuXfV1oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UuXfV1o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UuXfV1o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acce' => ['privates', '.errored..service_locator.UuXfV1o.App\\Entity\\Acces', NULL, 'Cannot autowire service ".service_locator.UuXfV1o": it needs an instance of "App\\Entity\\Acces" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'acce' => 'App\\Entity\\Acces',
            'entityManager' => '?',
        ]);
    }
}
