<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AccesType' shared autowired service.
     *
     * @return \App\Form\AccesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AccesType.php';

        return $container->privates['App\\Form\\AccesType'] = new \App\Form\AccesType();
    }
}
