<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pO_aEi_.App\Controller\OrganisationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.pO_aEi_'] ?? $container->load('get_ServiceLocator_POAEiService'));

        if (isset($container->privates['.service_locator.pO_aEi_.App\\Controller\\OrganisationController::edit()'])) {
            return $container->privates['.service_locator.pO_aEi_.App\\Controller\\OrganisationController::edit()'];
        }

        return $container->privates['.service_locator.pO_aEi_.App\\Controller\\OrganisationController::edit()'] = $a->withContext('App\\Controller\\OrganisationController::edit()', $container);
    }
}
