<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5s9Lt6G.App\Controller\PointageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5s9Lt6G.App\\Controller\\PointageController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointage' => ['privates', '.errored..service_locator.5s9Lt6G.App\\Entity\\Pointage', NULL, 'Cannot autowire service ".service_locator.5s9Lt6G": it needs an instance of "App\\Entity\\Pointage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pointage' => 'App\\Entity\\Pointage',
        ]))->withContext('App\\Controller\\PointageController::show()', $container);
    }
}
