<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZone2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wxYej41.App\Entity\Zone' shared service.
     *
     * @return \App\Entity\Zone
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wxYej41": it needs an instance of "App\\Entity\\Zone" but this type has been excluded in "config/services.yaml".');
    }
}
