<?php

namespace ContainerAX5NcXU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wxYej41.App\Controller\ZoneController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.wxYej41'] ?? $container->load('get_ServiceLocator_WxYej41Service'));

        if (isset($container->privates['.service_locator.wxYej41.App\\Controller\\ZoneController::edit()'])) {
            return $container->privates['.service_locator.wxYej41.App\\Controller\\ZoneController::edit()'];
        }

        return $container->privates['.service_locator.wxYej41.App\\Controller\\ZoneController::edit()'] = $a->withContext('App\\Controller\\ZoneController::edit()', $container);
    }
}
