<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLgrT3Co\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLgrT3Co/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLgrT3Co.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLgrT3Co\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLgrT3Co\App_KernelDevDebugContainer([
    'container.build_hash' => 'LgrT3Co',
    'container.build_id' => 'fa48f9df',
    'container.build_time' => 1746713940,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLgrT3Co');
