<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7HD49W1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7HD49W1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7HD49W1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7HD49W1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7HD49W1\App_KernelDevDebugContainer([
    'container.build_hash' => '7HD49W1',
    'container.build_id' => '955a5681',
    'container.build_time' => 1747564626,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7HD49W1');
