<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSuUm5Ge\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSuUm5Ge/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSuUm5Ge.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSuUm5Ge\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSuUm5Ge\App_KernelDevDebugContainer([
    'container.build_hash' => 'SuUm5Ge',
    'container.build_id' => '1519cf9b',
    'container.build_time' => 1745173234,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSuUm5Ge');
