<?php

namespace ContainerSupPdX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KutXhtj.App\Controller\BadgeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KutXhtj.App\\Controller\\BadgeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badge' => ['privates', '.errored..service_locator.KutXhtj.App\\Entity\\Badge', NULL, 'Cannot autowire service ".service_locator.KutXhtj": it needs an instance of "App\\Entity\\Badge" but this type has been excluded in "config/services.yaml".'],
        ], [
            'badge' => 'App\\Entity\\Badge',
        ]))->withContext('App\\Controller\\BadgeController::show()', $container);
    }
}
