<?php

namespace ContainerSupPdX0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7H9QsQ_.App\Controller\OrganisationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7H9QsQ_.App\\Controller\\OrganisationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'organisation' => ['privates', '.errored..service_locator.7H9QsQ_.App\\Entity\\Organisation', NULL, 'Cannot autowire service ".service_locator.7H9QsQ_": it needs an instance of "App\\Entity\\Organisation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'organisation' => 'App\\Entity\\Organisation',
        ]))->withContext('App\\Controller\\OrganisationController::show()', $container);
    }
}
