<?php

namespace ContainerO3UXjDG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccesControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ONyVVxL.App\Controller\AccesController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ONyVVxL.App\\Controller\\AccesController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'accesRepository' => ['privates', 'App\\Repository\\AccesRepository', 'getAccesRepositoryService', true],
        ], [
            'accesRepository' => 'App\\Repository\\AccesRepository',
        ]))->withContext('App\\Controller\\AccesController::index()', $container);
    }
}
