<?php

namespace ContainerO3UXjDG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeuseControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..hDjHWY.App\Controller\BadgeuseController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..hDjHWY.App\\Controller\\BadgeuseController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badgeuseRepository' => ['privates', 'App\\Repository\\BadgeuseRepository', 'getBadgeuseRepositoryService', true],
        ], [
            'badgeuseRepository' => 'App\\Repository\\BadgeuseRepository',
        ]))->withContext('App\\Controller\\BadgeuseController::index()', $container);
    }
}
