<?php

namespace ContainerO3UXjDG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getZoneControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YOL0uQe.App\Controller\ZoneController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YOL0uQe.App\\Controller\\ZoneController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zoneRepository' => ['privates', 'App\\Repository\\ZoneRepository', 'getZoneRepositoryService', true],
        ], [
            'zoneRepository' => 'App\\Repository\\ZoneRepository',
        ]))->withContext('App\\Controller\\ZoneController::index()', $container);
    }
}
