<?php

namespace Container7HD49W1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganisationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\OrganisationType' shared autowired service.
     *
     * @return \App\Form\OrganisationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/OrganisationType.php';

        return $container->privates['App\\Form\\OrganisationType'] = new \App\Form\OrganisationType();
    }
}
