<?php

namespace ContainerFpJotCr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ydkNY9v.App\Controller\AccesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ydkNY9v.App\\Controller\\AccesController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acce' => ['privates', '.errored..service_locator.ydkNY9v.App\\Entity\\Acces', NULL, 'Cannot autowire service ".service_locator.ydkNY9v": it needs an instance of "App\\Entity\\Acces" but this type has been excluded in "config/services.yaml".'],
        ], [
            'acce' => 'App\\Entity\\Acces',
        ]))->withContext('App\\Controller\\AccesController::show()', $container);
    }
}
