<?php

namespace ContainerFpJotCr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeuseControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D21ZqPi.App\Controller\BadgeuseController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D21ZqPi.App\\Controller\\BadgeuseController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'badgeuse' => ['privates', '.errored..service_locator.D21ZqPi.App\\Entity\\Badgeuse', NULL, 'Cannot autowire service ".service_locator.D21ZqPi": it needs an instance of "App\\Entity\\Badgeuse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'badgeuse' => 'App\\Entity\\Badgeuse',
        ]))->withContext('App\\Controller\\BadgeuseController::show()', $container);
    }
}
