<?php

namespace ContainerFpJotCr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BGy84Dx.App\Entity\Badge' shared service.
     *
     * @return \App\Entity\Badge
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BGy84Dx": it needs an instance of "App\\Entity\\Badge" but this type has been excluded in "config/services.yaml".');
    }
}
